#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#  DAHOOM · install the `dahoomdev` shortcut
#  Installs a tiny global command called `dahoomdev` on THIS machine
#  that launches tools/license-panel.sh directly, from anywhere —
#  no need to `cd` into the fm repo first.
#
#  Usage (run once, from inside the fm repo):
#      bash tools/install-dahoomdev-cmd.sh
#
#  After that, just type:  dahoomdev
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail
cd "$(dirname "$0")/.."
REPO_DIR="$(pwd)"
PANEL_SCRIPT="$REPO_DIR/tools/license-panel.sh"

if [ ! -f "$PANEL_SCRIPT" ]; then
    echo "❌ Could not find tools/license-panel.sh under $REPO_DIR" >&2
    exit 1
fi

write_wrapper() {
    local dest="$1"
    cat > "$dest" <<EOF
#!/usr/bin/env bash
# Auto-generated by tools/install-dahoomdev-cmd.sh — do not edit by hand.
# Re-run that script if you move the fm repo to a new path.
exec bash "$PANEL_SCRIPT" "\$@"
EOF
    chmod +x "$dest"
}

if [ -w /usr/local/bin ] 2>/dev/null; then
    write_wrapper /usr/local/bin/dahoomdev
    echo "✅ Installed: /usr/local/bin/dahoomdev"
elif command -v sudo >/dev/null 2>&1; then
    TMP="$(mktemp)"
    write_wrapper "$TMP"
    sudo install -m 755 "$TMP" /usr/local/bin/dahoomdev
    rm -f "$TMP"
    echo "✅ Installed: /usr/local/bin/dahoomdev (via sudo)"
else
    mkdir -p "$HOME/.local/bin"
    write_wrapper "$HOME/.local/bin/dahoomdev"
    echo "✅ Installed: $HOME/.local/bin/dahoomdev"
    case ":$PATH:" in
        *":$HOME/.local/bin:"*) ;;
        *)
            echo "⚠️  $HOME/.local/bin is not on your PATH yet. Add this to ~/.bashrc:"
            echo "      export PATH=\"\$HOME/.local/bin:\$PATH\""
            ;;
    esac
fi

echo "Now just type:  dahoomdev"
